"""diagnostico_turma

Revision ID: 56abdbf6064f
Revises: 993ae9d17454
Create Date: 2026-06-25 14:49:32.789535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56abdbf6064f'
down_revision: Union[str, Sequence[str], None] = '993ae9d17454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostico_turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('pontos_fracos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recomendacoes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('modelo_versao', sa.String(length=40), nullable=False),
    sa.Column('gerado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostico_turma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostico_turma_simulado_id'), ['simulado_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostico_turma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostico_turma_simulado_id'))

    op.drop_table('diagnostico_turma')
    # ### end Alembic commands ###
