"""resultados_simulado

Revision ID: 6fdd9fc410a8
Revises: 619512f19343
Create Date: 2026-06-25 19:06:49.852849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdd9fc410a8'
down_revision: Union[str, Sequence[str], None] = '619512f19343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_simulado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulado_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('acertos', sa.Integer(), nullable=False),
    sa.Column('respondidas', sa.Integer(), nullable=False),
    sa.Column('total_questoes', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulado_id'], ['simulados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulado_id', 'aluno_id', name='uq_resultado_simulado_aluno')
    )
    with op.batch_alter_table('resultados_simulado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultados_simulado_aluno_id'), ['aluno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resultados_simulado_simulado_id'), ['simulado_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_simulado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultados_simulado_simulado_id'))
        batch_op.drop_index(batch_op.f('ix_resultados_simulado_aluno_id'))

    op.drop_table('resultados_simulado')
    # ### end Alembic commands ###
