"""predicao_risco

Revision ID: 78c8cd317e01
Revises: 993ae9d17454
Create Date: 2026-06-25 12:59:39.039696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78c8cd317e01'
down_revision: Union[str, Sequence[str], None] = '993ae9d17454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predicao_risco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('score_risco', sa.Float(), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.Column('fatores', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('modelo_versao', sa.String(length=40), nullable=False),
    sa.Column('calculada_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predicao_risco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predicao_risco_aluno_id'), ['aluno_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predicao_risco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predicao_risco_aluno_id'))

    op.drop_table('predicao_risco')
    # ### end Alembic commands ###
